### ISSUE TITLE
Stylize Scan.jsx

### ISSUE THREAD

**Issue by Yogeshwar-CM** [Yogeshwar-CM/Techno-Cart#1]
Stylize Scan.jsx with your frontend skills

**Comment by vikramnagwal** [comment]
It seems that there is no .env.sample file available to specify the variables that are present in the .env file

**Comment by Yogeshwar-CM** [comment]
> It seems that there is no .env.sample file available to specify the variables that are present in the .env file

I have not used env for client side
You may simply format css and the jsx file

**Comment by vikramnagwal** [comment]
Yes, I need the backend as well because I want to run your project on my local machine to watch styling.

**Comment by Yogeshwar-CM** [comment]
> Yes, I need the backend as well because I want to run your project on my local machine to watch styling.

Check now
